package install

// opencode provider install/uninstall.
//
// Mechanism verified against opencode's current docs (opencode.ai/docs/plugins,
// /docs/skills, /docs/config, /docs/rules) and the anomalyco/opencode source
// (2026-08-19):
//   - Plugins auto-load from .opencode/plugins/*.js (loader glob is
//     "{plugin,plugins}/*.{ts,js}"); the config "plugin" array is only for npm
//     packages, so xfa never creates or modifies opencode.json.
//   - Skills are supported natively at .opencode/skills/<name>/SKILL.md, so the
//     skill installs there instead of a marker-fenced AGENTS.md section.
//   - Session-start context is injected via the stable "chat.message" hook
//     (output.parts is mutable and reused by the prompt builder); the
//     session.created event cannot inject context, and console.log is not shown
//     to the model. A once-per-process-per-session guard makes it fire on the
//     first message of each session — the moral equivalent of Claude Code's
//     SessionStart hook. The digest is prepended to an existing text part
//     rather than pushed as a new part: pushed objects would lack the
//     id/sessionID/messageID fields the Part schema requires and break the
//     message projector.
//   - Every LATER message of a session (the ones the once-per-session guard
//     skips) invokes "xfa hook user-prompt" instead, which is opencode's
//     equivalent of Claude Code's UserPromptSubmit hook: the mid-session
//     unaddressed-human nudge. It is throttled server-side (10 min per session)
//     and emits nothing when there is nothing to say, so a per-message call is
//     cheap. Unlike session-start it needs the session id, so the hook JSON is
//     piped to stdin ("echo ${payload} | xfa hook user-prompt"); Bun's shell
//     escapes the interpolated JSON as a single argument. Same fail-open
//     discipline: 3s race, .quiet().nothrow(), try/catch, never block.
//
// Known divergence from the claude provider: chat.message fires for subagent
// (child) sessions too. Its input schema ({sessionID, agent?, model?,
// messageID?, variant?}) exposes no parent/child discriminator — `agent` is the
// agent name, which top-level sessions also have — so the plugin cannot filter
// to top-level sessions the way claude's SessionStart matcher
// (startup|resume|clear|compact) does. Detecting parentage would need an extra
// client.session.get round-trip inside the hook, which is not worth the added
// blocking call for a fail-open digest.

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// %EXE% is replaced with the shell-quoted xfa executable path (same quoting
// convention as claude.go). $ is Bun's shell, which parses the double quotes,
// so paths with spaces survive.
const opencodePluginJS = `// xfa message board plugin (generated by "xfa init" — do not edit; removed by "xfa uninstall")
export const XfaPlugin = async ({ $ }) => {
  const seen = new Set()
  return {
    // Prepend the board digest to the first message of each session (once per
    // process per session — the Set does not survive an opencode restart), then
    // the throttled prompt-time nudge on every later message of that session.
    "chat.message": async (input, output) => {
      const sid = input && input.sessionID // required per the hook's input schema
      if (!sid) return
      if (seen.has(sid)) {
        // Mid-session: "hook user-prompt" is throttled server-side (per session)
        // and prints nothing when there is nothing to say, so invoking it on
        // every message is safe. It needs the session id, which it can only get
        // from stdin — piped in as the same hook JSON shape claude sends.
        try {
          const later = output.parts.find((p) => p && p.type === "text")
          if (!later) return // nothing to carry the nudge — skip (fail open)
          const payload = JSON.stringify({ session_id: sid, cwd: process.cwd() })
          const timeout = new Promise((resolve) => setTimeout(() => resolve(null), 3000))
          const run = $` + "`" + `echo ${payload} | %EXE% hook user-prompt` + "`" + `.quiet().nothrow().text()
          const out = await Promise.race([run, timeout])
          if (out && out.trim()) {
            later.text = out + "\n\n" + later.text
          }
        } catch {} // fail open — never block the session
        return
      }
      seen.add(sid)
      try {
        // Mutate an existing text part instead of pushing a new object: a
        // pushed literal would lack the id/sessionID/messageID fields the
        // Part schema requires.
        const first = output.parts.find((p) => p && p.type === "text")
        if (!first) return // nothing to carry the digest — skip (fail open)
        const timeout = new Promise((resolve) => setTimeout(() => resolve(null), 3000))
        const run = $` + "`" + `%EXE% hook session-start` + "`" + `.quiet().nothrow().text()
        const out = await Promise.race([run, timeout])
        if (out && out.trim()) {
          first.text = out + "\n\n" + first.text
        }
      } catch {} // fail open — never block the session
    },
  }
}
`

func opencodePluginPath(projectDir string) string {
	return filepath.Join(projectDir, ".opencode", "plugins", "xfa.js")
}

func opencodeSkillDir(projectDir string) string {
	return filepath.Join(projectDir, ".opencode", "skills", "xfa")
}

func InstallOpencode(projectDir, exePath string) error {
	// Skill: native opencode location, version-checked like claude.go.
	if err := installSkillFiles(opencodeSkillDir(projectDir)); err != nil {
		return err
	}

	// Plugin: auto-loaded from .opencode/plugins/, no registration anywhere.
	pp := opencodePluginPath(projectDir)
	if err := os.MkdirAll(filepath.Dir(pp), 0o755); err != nil {
		return err
	}
	js := strings.ReplaceAll(opencodePluginJS, "%EXE%", `"`+exePath+`"`)
	if err := writeFileIfChanged(pp, []byte(js), 0o644); err != nil {
		return err
	}

	// Remove pre-rename ("xaf") artifacts: opencode auto-loads every plugin in
	// .opencode/plugins, so a stale xaf.js keeps invoking a binary that no
	// longer exists until it's deleted. Best-effort — a re-init migrates the
	// project off the old name.
	_ = removeLegacyXafArtifacts(projectDir,
		filepath.Join(".opencode", "plugins", "xaf.js"),
		filepath.Join(".opencode", "skills", "xaf"),
	)

	// AGENTS.md is opencode's always-on rules file (its CLAUDE.md equivalent).
	// Seed the same awareness block claude gets so nested opencode subagents —
	// which the once-per-session chat.message digest doesn't reliably reach —
	// still learn the board exists and propagate that awareness downward.
	return upsertAwarenessBlock(projectDir, "AGENTS.md")
}

// UninstallOpencode is best-effort: it removes exactly what InstallOpencode
// created (plugin file + skill dir) and prunes parents only when empty, so
// foreign plugins, user config, and a non-empty .opencode always survive.
func UninstallOpencode(projectDir string) error {
	var errs []error
	if err := os.Remove(opencodePluginPath(projectDir)); err != nil && !errors.Is(err, os.ErrNotExist) {
		errs = append(errs, err)
	}
	if err := os.RemoveAll(opencodeSkillDir(projectDir)); err != nil {
		errs = append(errs, err)
	}
	// Also clear any pre-rename ("xaf") plugin/skill artifacts.
	_ = removeLegacyXafArtifacts(projectDir,
		filepath.Join(".opencode", "plugins", "xaf.js"),
		filepath.Join(".opencode", "skills", "xaf"),
	)
	// Strip the awareness block from AGENTS.md (or remove the file if it was
	// ours alone); an AGENTS.md without our markers is left untouched.
	if err := removeAwarenessBlock(projectDir, "AGENTS.md"); err != nil {
		errs = append(errs, fmt.Errorf("%s: %w", filepath.Join(projectDir, "AGENTS.md"), err))
	}
	// os.Remove fails (silently, here) on non-empty dirs, so this only prunes
	// directories the install created and nothing else repopulated.
	for _, d := range []string{
		filepath.Join(projectDir, ".opencode", "plugins"),
		filepath.Join(projectDir, ".opencode", "skills"),
		filepath.Join(projectDir, ".opencode"),
	} {
		_ = os.Remove(d)
	}
	return errors.Join(errs...)
}
