package install

// pi provider install/uninstall.
//
// Mechanism verified against pi's docs (pi.dev/docs/latest, 2026-08-25):
//   - Extensions are TypeScript files auto-discovered at
//     .pi/extensions/*.ts and loaded via jiti — no build step and no config
//     file to register them in, so xfa writes exactly one generated file and
//     never touches any JSON config.
//   - Skills are Claude-compatible at .pi/skills/<name>/SKILL.md, so xfa's
//     SKILL.md installs there as-is, version-stamped like the other providers.
//   - Context is injected via the "before_agent_start" event — the only event
//     that both fires on every user prompt (before the agent loop) and can
//     inject a persistent context message through its returned { message }.
//     A once-per-process-per-session guard picks "hook session-start" for the
//     first prompt of a session and the throttled "hook user-prompt" nudge for
//     every later one — the moral equivalents of Claude Code's SessionStart
//     and UserPromptSubmit hooks, mirroring the opencode plugin.
//   - Trust caveat: pi only loads .pi/extensions and .pi/skills in projects
//     the human has trusted (~/.pi/agent/trust.json). Nothing to do at
//     install time; the README documents it. AGENTS.md-family context files
//     load regardless of trust, so the awareness block goes to AGENTS.md —
//     the same file opencode seeds.
//   - No stop-hook equivalent, mirroring opencode: pi has no post-turn
//     injection point that reaches the agent before shutdown.
//   - No legacy "xaf" cleanup: pi postdates the rename.

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// %EXE% is replaced with the quoted xfa executable path (same convention as
// claude.go/opencode.go). It lands inside a JS string literal passed to
// execFile's file argument — no shell parsing — so paths with spaces survive.
const piExtensionTS = `// xfa message board extension (generated by "xfa init" — do not edit; removed by "xfa uninstall")
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { execFile } from "node:child_process";

const seen = new Set<string>();

// Run the xfa hook fail-open: pipe the payload to stdin, bound by timeoutMs,
// and resolve the trimmed raw stdout — the same extraction the opencode
// plugin uses — or "" on any error. Never rejects.
function run(exe: string, args: string[], stdin: string, timeoutMs: number): Promise<string> {
  return new Promise((resolve) => {
    try {
      const child = execFile(exe, args, { timeout: timeoutMs }, (err, stdout) => {
        resolve(err ? "" : String(stdout ?? "").trim());
      });
      child.stdin?.on("error", () => {});
      child.stdin?.end(stdin);
    } catch {
      resolve("");
    }
  });
}

export default function (pi: ExtensionAPI) {
  // Inject the board digest on the first prompt of each session (once per
  // process per session — the Set does not survive a pi restart), then the
  // throttled prompt-time nudge on every later prompt of that session.
  pi.on("before_agent_start", async (_event, ctx) => {
    try {
      const sid = ctx.sessionManager.getSessionId() ?? "";
      const first = !seen.has(sid);
      seen.add(sid);
      const sub = first ? "session-start" : "user-prompt";
      const payload = JSON.stringify({ session_id: sid, cwd: ctx.cwd });
      const out = await run(%EXE%, ["hook", sub], payload, 3000);
      if (!out) return;
      // display: false — the digest reaches the LLM without cluttering the TUI.
      return { message: { customType: "xfa", content: out, display: false } };
    } catch {} // fail open — never block the session
  });
}
`

func piExtensionPath(projectDir string) string {
	return filepath.Join(projectDir, ".pi", "extensions", "xfa.ts")
}

func piSkillDir(projectDir string) string {
	return filepath.Join(projectDir, ".pi", "skills", "xfa")
}

func InstallPi(projectDir, exePath string) error {
	// Skill: native pi location (Claude-compatible frontmatter),
	// version-checked like claude.go.
	if err := installSkillFiles(piSkillDir(projectDir)); err != nil {
		return err
	}

	// Extension: auto-discovered from .pi/extensions/, no registration anywhere.
	ep := piExtensionPath(projectDir)
	if err := os.MkdirAll(filepath.Dir(ep), 0o755); err != nil {
		return err
	}
	ts := strings.ReplaceAll(piExtensionTS, "%EXE%", `"`+exePath+`"`)
	if err := writeFileIfChanged(ep, []byte(ts), 0o644); err != nil {
		return err
	}

	// AGENTS.md loads regardless of project trust (unlike .pi/), so the
	// awareness block there reaches agents even before the human trusts the
	// project — and it is the same file opencode seeds, so the upsert is
	// naturally shared between the two providers.
	return upsertAwarenessBlock(projectDir, "AGENTS.md")
}

// UninstallPi is best-effort: it removes exactly what InstallPi created
// (extension file + skill dir) and prunes parents only when empty, so foreign
// extensions, foreign skills, and a non-empty .pi always survive.
func UninstallPi(projectDir string) error {
	var errs []error
	if err := os.Remove(piExtensionPath(projectDir)); err != nil && !errors.Is(err, os.ErrNotExist) {
		errs = append(errs, err)
	}
	if err := os.RemoveAll(piSkillDir(projectDir)); err != nil {
		errs = append(errs, err)
	}
	// Strip the awareness block from AGENTS.md (or remove the file if it was
	// ours alone); an AGENTS.md without our markers is left untouched.
	if err := removeAwarenessBlock(projectDir, "AGENTS.md"); err != nil {
		errs = append(errs, fmt.Errorf("%s: %w", filepath.Join(projectDir, "AGENTS.md"), err))
	}
	// os.Remove fails (silently, here) on non-empty dirs, so this only prunes
	// directories the install created and nothing else repopulated.
	for _, d := range []string{
		filepath.Join(projectDir, ".pi", "extensions"),
		filepath.Join(projectDir, ".pi", "skills"),
		filepath.Join(projectDir, ".pi"),
	} {
		_ = os.Remove(d)
	}
	return errors.Join(errs...)
}
